### ISSUE TITLE
distcc fails to handle standalone -Wp,-MT,target gcc option

### ISSUE THREAD

**Issue by lersek** [distcc/distcc#248] opened 2017-12-18 12:31 UTC
**Distcc version**: `distcc-3.2rc1-11` (from Fedora)

**Issue description**: Linux kernel commit baa1973ebcf6 ("tools build: Fix objtool build with clang", 2016-12-05) split gcc `-Wp` options of the form

    -Wp,-MD,$(depfile),-MT,$@

to separate options of the form

    -Wp,-MD,$(depfile) -Wp,-MT,$@

(This Linux kernel commit was released as part of Linux v4.10.) As a result, distcc can no longer build the kernel; compilation fails with:

      HOSTCC   .../tools/objtool/fixdep.o
    gcc: fatal error: no input files
    compilation terminated.
    distcc[14013] ERROR: compile (null) on localhost failed with exit code 4
    cat: .../tools/objtool/.fixdep.o.d: No such file or directory

**Additional info**:
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=baa1973ebcf6a7bd15522a5b6a35a8fefd6cb232
* I found the kernel commit exposing the distcc issue via kernel bisection, between v4.8 and v4.13.11

**Comment by shawnl** [comment] 2017-12-19 04:14
I can reproduce this on Fedora, but not on Ubuntu/Debian

**Comment by shawnl** [comment] 2017-12-19 05:44
duplicate of bug #83, which fix (6 years old) did not make it into 3.2-rc1.

**Comment by lersek** [comment] 2017-12-19 10:05
Many thanks for confirming, and also for the pointer to the patch -- I've now filed a Fedora RHBZ as well, so they can apply the patch (similarly to Debian and Ubuntu) before a new upstream distcc release becomes available: https://bugzilla.redhat.com/show_bug.cgi?id=1527368

Thanks!

**Comment by lersek** [comment] 2017-12-20 11:18
The patch at https://storage.googleapis.com/google-code-attachments/distcc/issue-83/comment-0/fixArgc.patch works for me; thank you.

**Comment by shawnl** [comment] 2018-02-25 14:27
Closed as duplicate of bug #83

**Closed by shawnl** 2018-02-25 14:27 UTC
