### ISSUE TITLE
Automatic name resolution and pump mode

### ISSUE THREAD

**Issue by nokiann** [distcc/distcc#199] opened 2016-09-24 09:08 UTC
At the moment I always have to look for IP changes and keep /etc/hosts up to date.
Is Avahi the only way to achieve automatic name resolution? 
Any way for an automatic name resolution and using pump mode?

The manpage states using hostnames is slower. That's because of the name resolution, but it shouldn't make a difference during compilation right?

**Comment by thinrope** [comment] 2016-09-24 17:10
Unless you are asking for mesh networking (I guess not), there needs to be some way to coordinate the distcc hosts. DNS is one way, direct scripting another.
For a semi-automatic configuration, new distcc servers will register at the DNS/DHCP and say it will add A the new IP address to A record like distcc.mydomain, though configuring number of jobs is hard.

Alternatively, a script at the DNS/DHCP host will add the new IP to a TXT record formatted like the contents of /etc/distcc/hosts. On each client machine, a script can pull that periodically and update /etc/distcc/hosts if needed. This may be integrated in distcc at some stage, if it works.

I agree that current situation is not easy, but can you suggest better way?

**Comment by nokianhunter** [comment] 2016-09-24 17:30
At the moment I search for a "one-server-per-network" solution. That should be a bit easier.
My suggestion:
Something like the icecream scheduler just without the load balancing stuff?
https://github.com/icecc/icecream

**Comment by TafThorne** [comment] 2016-09-27 10:14
> Is Avahi the only way to achieve automatic name resolution? 
No.  DNS, mDNS, file and anything else that can be added under '/etc/nsswitch.conf' on a Linux box can resolve names.  

> Any way for an automatic name resolution and using pump mode?
I would assume anything that does a name resolution can work with pump mode. Sounds like @thinrope  has more direct experience though.  

> The manpage states using hostnames is slower. That's because of the name resolution, but it shouldn't make a difference during compilation right?
It is slower because a name must be resolved.  If your client machine (the one running pump) will cache the result of a name look up for a while the delay across the whole build will be small.  If the client machine looks up the IP address for a name every time it tries to contact the named host there will be a larger accumulated delay over your build.  If pump mode is performing a name resolution for every file in your build that might be hundreds of thousands of lookups for a large build job.  

For DNS on Ubuntu and Debian I think the name is cached for a short while so you should not see hundreds of lookups per second.  I may be incorrect about that and it is possible to configure your system to behave in other ways.  I cannot say what caching, if any, is performed for other name resolution protocols.  

Reading the /etc/hosts or /etc/distcc/hosts file from a local filesystem should be very fast.  If the file does not chance I would expect it to end up cached in RAM resulting in a very fast read result.

**Comment by TafThorne** [comment] 2016-09-27 10:24
> Something like the icecream scheduler just without the load balancing stuff?

Does pump mode and other bits of distcc not work on a round robin basis when provided a list?  That would mean providing 3 targets would already causes it to schedule builds evenly between each node.  

If you want a slightly smarter scheduler there are several mentioned on the old online [documentation page](https://cdn.rawgit.com/distcc/distcc/9a09372bd3f420cdd7021e52eda14fa536a3c10e/doc/web/index.html).  
---

<p>
     There are several tools available separately that 
     enhance or complement distcc:

<ul>
       <li>
         <a href="http://ccache.samba.org/">ccache</a>
	 caches compiler output to accelerate builds.
      <li>
       <a href="http://dmucs.sourceforge.net/">dmucs</a> helps distcc select
       appropriate servers.

      <li>
        <a href="http://ccontrol.ozlabs.org/">ccontrol</a>  
	gives centralized control of parallelism, caching and distribution 
	even while the build is running.


      <li>
        <a href="http://kegel.com/crosstool/">crosstool</a>
        automates building cross-compilation toolchains.
       
    <li><a href="http://research.edm.luc.ac.be/~tvanlaerhoven/index.php?selected=projects">distccWebView</a> is a CGI to show which of your
  servers are up and running.

  <li>
<a href="http://www.snookles.com/erlang/tcpbalance/">tcpbalance</a>
   is a load-balancing TCP proxy written in Erlang that works well with
   distcc.

</ul>
</p>

---
ccontrol sounds like the sort of think you want.

**Comment by nokianhunter** [comment] 2016-09-29 08:08
> That would mean providing 3 targets would already causes it to schedule builds evenly between each node.
I think icecream goes one step further and also watches the overall load of each node. So people currently working on the node won't recognize the additional load that much.

Scheduling is not too important too me, but ease of use. And having compile errors thrown when nodes defined in DISTCC_HOSTS are offline is not so cool. You could say it's a feature, but when I want to check the working nodes I simply use distccmon.

> DNS, mDNS, file and anything else that can be added under '/etc/nsswitch.conf' on a Linux box can resolve names.
The best thing would be if the network discovery and name resolution are integrated with the daemon.
No config file editing. Don't know about the overhead though.

**Comment by TafThorne** [comment] 2016-09-29 09:09
> Scheduling is not too important too me, but ease of use. And having compile errors thrown when nodes defined in DISTCC_HOSTS are offline is not so cool. 

I think you would need the ccontrol system if you expect nodes to dynamically come and go.  I think that distcc was designed on the expectation that there would be a fixed, dedicated set of server machines accessed by a dynamic set of clients.  

>The best thing would be if the network discovery and name resolution are integrated with the daemon.

That is possibly going over the bounds of making a simple tool that does one thing well.  Anytime you make a system more dynamic it tends to get less performant.  

It sounds reasonable that distcc could look at the given set of hosts, attempt to ping or access them all in someway, warn about missing one and continue on the assumption that one which are live at the start will be live all the way through.  It might even be possible to cope with resubmitting a job to a different server if it obviously failed because of server going offline.   

It is making things more complicated than a fixed set of servers.  Something would have to spend the cycles checking which machines are online, how loaded they are and maintaining a list of preferences.  If your client is quite weak that might add a fair bit of overhead.  That is why a separate ccontrol system running on a separate server was/is desirable.

**Comment by nokianhunter** [comment] 2016-09-29 16:23
> That is why a separate ccontrol system running on a separate server was/is desirable.
But ccontrol doesn't manage name resolution.
You are right with the overhead. Probably it's best to leave things as they are.

**Comment by TafThorne** [comment] 2016-09-29 16:28
> But ccontrol doesn't manage name resolution.

If you have only Linux and Mac OS systems I would recommend you setup Avahi to provide an mDNS service.  Vague details for Avahi on Ubunut can be found at https://help.ubuntu.com/community/HowToZeroconf 

mDNS lets each machine answer its own name for a resolution request.  You have to use a _hostname_.local style name to reference mDNS names.

**Comment by nokianhunter** [comment] 2016-09-29 17:13
Will it be supported by pump mode any time in the future?
>> But ccontrol doesn't manage name resolution.
> If you have only Linux and Mac OS systems I would recommend you setup Avahi to provide an mDNS service.  Vague details for Avahi on Ubunut can be found at https://help.ubuntu.com/community/HowToZeroconf
>
> mDNS lets each machine answer its own name for a resolution request.  You have to use a _hostname_.local style name to reference mDNS names.
>

**Comment by TafThorne** [comment] 2016-09-30 08:54
> Will it be supported by pump mode any time in the future?

If by _it_ you mean mDNS then it is supported now.  Name resolution is up to the host system, whether it uses a hosts table, DNS, mDNS or other.   To be fair I have not tested this assertion but I would be surprised to hear that it does not work.

**Comment by TafThorne** [comment] 2016-12-15 11:29
I think we got as far as deciding that it is not distcc's job to do name resolution and provided some alternative work flows.  On that basis I will reject/close this issue unless someone can see anything worth keeping it for?

**Closed by TafThorne** 2016-12-15 11:29 UTC
Labels: enhancement, invalid, wontfix
