### ISSUE TITLE
running distcc in fakeroot breaks dcc_mkdir

### ISSUE THREAD

**Issue by ScrumpyJack** [distcc/distcc#166] opened 2015-12-08 17:11 UTC
Is it possible to create those lock and state folders elsewhere than in $HOME as running distcc in fakeroot means id=0 but absolute /root is not available.

distcc[24737](dcc_mkdir) ERROR: mkdir '/root/.distcc' failed: Permission denied

Let me know if you need more information on how to reproduce this

distcc 3.1
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/5.2.0/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-5.2.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 5.2.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-esp --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib
Thread model: posix
gcc version 5.2.0 (Alpine 5.2.0)

**Comment by ScrumpyJack** [comment] 2015-12-09 07:42
I should have looked more closely. DISTCC_DIR will fix this

**Comment by shawnl** [comment] 2017-11-05 01:20
if this is not a bug close it

**Comment by shawnl** [comment] 2018-03-01 18:52
reporter says this is not a bug

**Closed by shawnl** 2018-03-01 18:52 UTC
